/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutModal: typeof import('./components/shell/AboutModal.vue')['default']
    AppShell: typeof import('./components/shell/AppShell.vue')['default']
    ImportConfirmModal: typeof import('./components/shell/ImportConfirmModal.vue')['default']
    LyricsLineList: typeof import('./components/shell/LyricsLineList.vue')['default']
    LyricsPanel: typeof import('./components/shell/LyricsPanel.vue')['default']
    LyricsPasteModal: typeof import('./components/shell/LyricsPasteModal.vue')['default']
    MainView: typeof import('./components/shell/MainView.vue')['default']
    MenuBar: typeof import('./components/shell/MenuBar.vue')['default']
    PreferencesModal: typeof import('./components/shell/PreferencesModal.vue')['default']
    ProjectValidationModal: typeof import('./components/shell/ProjectValidationModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBar: typeof import('./components/shell/StatusBar.vue')['default']
    TimingPointControls: typeof import('./components/shell/TimingPointControls.vue')['default']
    TimingPointList: typeof import('./components/shell/TimingPointList.vue')['default']
    TimingPointsPanel: typeof import('./components/shell/TimingPointsPanel.vue')['default']
    TransportBar: typeof import('./components/shell/TransportBar.vue')['default']
    UnsavedChangesDialog: typeof import('./components/shell/UnsavedChangesDialog.vue')['default']
    VerticalSliderPopover: typeof import('./components/shell/VerticalSliderPopover.vue')['default']
    WordSplitBar: typeof import('./components/shell/WordSplitBar.vue')['default']
  }
}
