/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./components/shell/AppShell.vue')['default']
    MainView: typeof import('./components/shell/MainView.vue')['default']
    MenuBar: typeof import('./components/shell/MenuBar.vue')['default']
    ModePanel: typeof import('./components/shell/ModePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransportBar: typeof import('./components/shell/TransportBar.vue')['default']
  }
}
